# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: SecryMasterCICDVariables
- name: 'BuildMessage'
  value: '$(Build.SourceVersionMessage)'

trigger:
- US555-test-utils

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: 'macOS-latest'
    steps:  

    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'

    - task: FlutterTest@0
      inputs:
        projectDirectory: 