# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: SecryMasterCICDVariables
- name: 'BuildMessage'
  value: '$(Build.SourceVersionMessage)'

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: 'macOS-latest'
    steps:

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'

    - task: FlutterTest@0
      inputs:
        projectDirectory: 

    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: 

    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: true
        apksignerKeystoreFile: key.jks
        apksignerKeystorePassword: $(keypassword)
        apksignerKeystoreAlias: $(keyalias)
        apksignerKeyPassword: $(keypassword)

    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(Build.artifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'drop'

    - task: AppCenterDistribute@3
      displayName: Run distribute
      inputs:
        serverEndpoint: 'SecryVSAppCenter'
        appSlug: 'Secry/SecryAndroid'
        appFile: 'build/app/outputs/flutter-apk/app-release.apk'
        releaseNotesOption: 'input'
        releaseNotesInput: '$(BuildMessage)'
        destinationType: 'groups'