name: secry
description: A new social media network
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.14.0
  firebase_analytics: ^9.1.3
  firebase_crashlytics: ^2.6.0
  firebase_auth: ^3.3.12

  # UI
  multiavatar: ^0.1.5
  flutter_svg: ^1.0.3
  theme_provider: ^0.5.0
  modal_bottom_sheet: ^2.0.1
  persistent_bottom_nav_bar_v2: ^4.1.8

  # Native features
  uuid: ^3.0.6
  image_picker: ^0.8.4+11

  # Localization
  intl: ^0.17.0
  easy_localization: ^3.0.0
  cupertino_icons: ^1.0.4

  # Dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  # Domain Driven Design
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  auto_route: ^3.2.4
  dartz: ^0.10.1
  country_code_picker: ^2.0.2

  # Database and requests
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  analyzer: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  build_runner: ^2.1.8
  injectable_generator: ^1.5.3
  auto_route_generator: ^3.2.3
  flutter_launcher_icons: ^0.9.2
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.5
  import_sorter: ^4.6.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/launcher/