name: secry
description: A new social media network
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.22.0
  firebase_analytics: ^9.3.4
  firebase_crashlytics: ^2.8.10
  firebase_auth: ^3.8.0

  # Social login(s)
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1
  twitter_login: ^4.2.3

  # UI
  multiavatar: ^0.1.5
  flutter_svg: ^1.1.5
  theme_provider: ^0.5.0
  modal_bottom_sheet: ^2.1.2
  persistent_bottom_nav_bar_v2: ^4.2.5

  # Native features
  uuid: ^3.0.6
  image_picker: ^0.8.5+3

  # Localization
  intl: ^0.17.0
  easy_localization: ^3.0.1
  cupertino_icons: ^1.0.5

  # Dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  # Domain Driven Design
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  auto_route: ^5.0.1
  dartz: ^0.10.1
  country_code_picker: ^2.0.2

  # Database and requests
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  analyzer: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  build_runner: ^2.2.1
  injectable_generator: ^1.5.4
  auto_route_generator: ^5.0.2
  flutter_launcher_icons: ^0.10.0
  retrofit_generator: ^4.0.3+2
  json_serializable: ^6.3.2
  import_sorter: ^4.6.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/launcher/
    - assets/fonts/google_icon.png
    - assets/fonts/facebook_icon.png
    - assets/fonts/apple_icon.png