name: secry
description: A new social media network
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_crashlytics: ^2.4.4
  firebase_auth: ^3.3.4

  # UI
  theme_provider: ^0.5.0

  # Localization
  intl: ^0.17.0
  easy_localization: ^3.0.0
  cupertino_icons: ^1.0.4

  # Dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.0

  # Domain Driven Design
  flutter_bloc: ^8.0.0
  freezed_annotation: ^0.15.0
  auto_route: ^3.1.3
  dartz: ^0.10.1
  country_picker: ^2.0.9
  country_code_picker: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.15.1+1
  build_runner: ^2.1.5
  injectable_generator: ^1.5.2
  auto_route_generator: ^3.1.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/launcher/